
# TO IMPORT THESE HASHMAPS, use
# import sampleDB.py
# or
# from sampleDB.py import HOUSES_COLLECTION -  to get just houses hashmap.
# or
# from sampleDB.py import VOLUNTEERS_COLLECTION - to get just volunteers hashmap.

VOLUNTEER_ID = 5
HOUSES_COLLECTION = {
    1:{
    "applicantName": "Alice Johnson",
    "streetAddress": "456 Elm Street",
    "phone": "555-987-6543",
    "alternatePhone": "555-555-5555",
    "primaryContact": "Bob Williams",
    "relationship": "Spouse",
    "contactPhone": "555-123-4567",
    "birthdate": "04/20/1990",
    "age": "33",
    "sex": "Female",
    "disabled": "No",
    "zipCode": "54321",
    "maritalStatus": "Married",
    "race": "African American",
    "ethnicity": "Non-Hispanic",
    "moveYear": "2015",
    "ownHome": "Yes",
    "mortgage": "Yes",
    "paymentsUpToDate": "Yes",
    "onlyResidence": "Yes",
    "renters": "No",
    "citation": "XYZ789",
    "appliedBefore": "Yes"
},
    2:{
    "applicantName": "David Smith",
    "streetAddress": "789 Oak Avenue",
    "phone": "555-222-3333",
    "alternatePhone": "555-444-5555",
    "primaryContact": "Sarah Davis",
    "relationship": "Friend",
    "contactPhone": "555-666-7777",
    "birthdate": "12/05/1982",
    "age": "41",
    "sex": "Male",
    "disabled": "No",
    "zipCode": "67890",
    "maritalStatus": "Single",
    "race": "Asian",
    "ethnicity": "Non-Hispanic",
    "moveYear": "2008",
    "ownHome": "No",
    "mortgage": "N/A",
    "paymentsUpToDate": "N/A",
    "onlyResidence": "Yes",
    "renters": "No",
    "citation": "PQR456",
    "appliedBefore": "No"
},
3:{
    "applicantName": "Mary Brown",
    "streetAddress": "321 Pine Road",
    "phone": "555-777-8888",
    "alternatePhone": "555-333-2222",
    "primaryContact": "John Anderson",
    "relationship": "Sibling",
    "contactPhone": "555-111-9999",
    "birthdate": "08/15/1975",
    "age": "48",
    "sex": "Female",
    "disabled": "Yes",
    "zipCode": "13579",
    "maritalStatus": "Divorced",
    "race": "Hispanic",
    "ethnicity": "Yes",
    "moveYear": "2005",
    "ownHome": "Yes",
    "mortgage": "Yes",
    "paymentsUpToDate": "Yes",
    "onlyResidence": "Yes",
    "renters": "No",
    "citation": "LMN123",
    "appliedBefore": "Yes"
},
4:{
    "applicantName": "Michael Wilson",
    "streetAddress": "567 Maple Lane",
    "phone": "555-444-9999",
    "alternatePhone": "555-666-8888",
    "primaryContact": "Emily Taylor",
    "relationship": "Spouse",
    "contactPhone": "555-222-1111",
    "birthdate": "03/10/1987",
    "age": "36",
    "sex": "Male",
    "disabled": "No",
    "zipCode": "24680",
    "maritalStatus": "Married",
    "race": "Caucasian",
    "ethnicity": "Non-Hispanic",
    "moveYear": "2012",
    "ownHome": "Yes",
    "mortgage": "Yes",
    "paymentsUpToDate": "Yes",
    "onlyResidence": "Yes",
    "renters": "No",
    "citation": "DEF567",
    "appliedBefore": "No"
}

}

VOLUNTEERS_COLLECTION = {
    1:{'first_name': "John",
        'last_name': "Doe",
        'email' : "example.com",
        'phone': "xxx-xxx-xxxx",
        'country': "USA",
        'address': "1234 example Drive",
        'skills': "Carpentry",
        'hours': 20,
        'people':[]},
    2:{'first_name': "Jane",
        'last_name': "Doe",
        'email' : "example.com",
        'phone': "xxx-xxx-xxxx",
        'country': "USA",
        'address': "1234 example Drive",
        'skills': "Carpentry",
        'hours': 20,
        'people':[]},
    3:{'first_name': "Joe",
        'last_name': "Doe",
        'email' : "example.com",
        'phone': "xxx-xxx-xxxx",
        'country': "USA",
        'address': "1234 example Drive",
        'skills': "Carpentry",
        'hours': 20,
        'people':[]},
    4:{'first_name': "Javier",
        'last_name': "Doe",
        'email' : "example.com",
        'phone': "xxx-xxx-xxxx",
        'country': "USA",
        'address': "1234 example Drive",
        'skills': "Carpentry",
        'hours': 20,
        'people':[]}
}

ADMIN_COLLECTION = {
    'exampleUser': {
        'password': 'examplePassword',
        'id': 1,
        'favorite_pet' : 'dog',
        'email': 'dummydata@org_name',
    }
}